import "./globals.css";
import "ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AmplifyProvider from "../lib/providers";
import '@aws-amplify/ui-react/styles.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <AmplifyProvider>
        <body className={inter.className}>{children}</body>
      </AmplifyProvider>
    </html>
  );
}
